### ISSUE TITLE
Client disconnects after a few seconds. 

### ISSUE THREAD

**Issue by DigitalCorrosion** [arsium/SpyBoxRat#1]
Running on Windows 10 VM. Fully updated. AV disabled etc. The client connects and goes offline in a few seconds. Tried various builds and options with the same outcome.

**Comment by arsium** [comment]
> Running on Windows 10 VM. Fully updated. AV disabled etc. The client connects and goes offline in a few seconds. Tried various builds and options with the same outcome.

I don't experiment this issue I will try to get it through my own VM it is strange I never got that through my own test :0

**Comment by DigitalCorrosion** [comment]
Will await you to recreate the issue.
